name: dighum101-housing
channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pandas
  - numpy
  - geopandas
  - shapely
  - matplotlib
  - jupyter
  - notebook
  - pip
  - pip:
      - esda
      - libpysal
